# Site settings
#title: Great New Blog Title
#author:
#  name: a b
#  email: your-email@domain.com
#description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
#markdown: kramdown
use_math: true



#remote_theme: pages-themes/midnight@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

#theme: minima
#remote_theme: benbalter/retlab



