# Site settings
#title: Great New Blog Title
#author:
#  name: a b
#  email: your-email@domain.com
#description: "Great site about Jekyll on GH-Pages."

# Build settings
#remote_theme: jekyll/minima #################
#markdown: kramdown
#use_math: true ###################





#remote_theme: pages-themes/midnight@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

#theme: minima
#remote_theme: benbalter/retlab



title: Aymeric # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  AI engineer
  <br><br>
  Web developer
  <br><br>
  <a href="https://www.linkedin.com/in/aymericaieng">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
