# Site settings
#title: Great New Blog Title
#author:
#  name: a b
#  email: your-email@domain.com
#description: "Great site about Jekyll on GH-Pages."

# Build settings
theme: minima
remote_theme: benbalter/retlab
markdown: kramdown
use_math: true

